let products = {
  darkAcademia: [
    {
      name: "Bronze Wood & Leather Cologne Intense",
      brand: "Jo Malone",
      category: null,
      price: 135,
      link: "https://www.jomalone.com/product/25946/62823/prodcat/colognes/bronze-wood-leather-cologne-intense",
      product_img: "darkacademia/DA_Images/JM_BWL_Cologne.png",
      brand_logo: "darkacademia/DA_Images/Jo_Malone_Logo.png",
    },
    {
      name: "Love Me Lipstick",
      brand: "M.A.C",
      category: "Coffee & Cigs",
      price: 22,
      link: "https://www.maccosmetics.com/product/13854/68146/Products/Makeup/Lips/Lipstick/Love-Me-Lipstick?gclid=Cj0KCQjw5uWGBhCTARIsAL70sLJ1Mrw4wSCkP4-9KUREBKZ1-NbXEUTDOah_OS8LqQahufqXNdaVCkwaAqviEALw_wcB&gclsrc=aw.ds#!/shade/Coffee_%26_Cigs",
      product_img: "darkacademia/DA_Images/MAC_Lipstick_C&C.png",
      brand_logo: "darkacademia/DA_Images/MAC_Logo.png",
    },
    {
      name: "Hairdresser's Invisible Oil Heat/UV Protective Primer",
      brand: "Bumble and bumble.",
      category: null,
      price: 13,
      link: "https://www.bumbleandbumble.com/product/19055/31247/style/pre-stylers/hairdressers-invisible-oil-heatuv-protective-primer#/sku/66176",
      product_img: "darkacademia/DA_Images/BB_HI_Primer.png",
      brand_logo: "darkacademia/DA_Images/B&B_Logo.png",
    },
    {
      name: "Travel Size Chocolate Soleil Bronzer",
      brand: "Too Faced",
      category: null,
      price: 16,
      link: "https://www.toofaced.com/product/23478/59163/face-makeup/bronzer/travel-size-chocolate-soleil-bronzer/long-lasting-buildable-bronzer",
      product_img: "darkacademia/DA_Images/TF_CS_Bronz.png",
      brand_logo: "darkacademia/DA_Images/Too_Faced_Logo.webp",
    },
    {
      name: "Sumptuous Extreme",
      brand: "Estee Lauder",
      category: "Black",
      price: 10,
      link: "https://www.esteelauder.com/product/631/37770/product-catalog/makeup/sumptuous-extreme/lash-multiplying-volume-mascara?shade=Black",
      product_img: "darkacademia/DA_Images/EL_SE_Mascara.png",
      brand_logo: "darkacademia/DA_Images/Estee_Lauder_Logo.png",
    },
    {
      name: "Lip Balm SPF 15",
      brand: "Bobbi Brown",
      category: null,
      price: 24,
      link: "https://www.bobbibrowncosmetics.com/product/17898/8221/new/travel-essentials/lip-balm-spf-15",
      product_img: "darkacademia/DA_Images/BB_Lip_Balm.png",
      brand_logo: "darkacademia/DA_Images/BBrown_Logo.webp",
    },
    {
      name: "Le Labo Design Book",
      brand: "Le Labo",
      category: null,
      price: 16,
      link: "https://www.lelabofragrances.com/design-book-345.html?size=os",
      product_img: "darkacademia/DA_Images/LL_Book.png",
      brand_logo: "darkacademia/DA_Images/Le_Labo_Logo.png",
    },
  ],
  ecore: [
    {
      name: "Dramatically Different Hydrating Jelly",
      brand: "Clinique",
      category: null,
      price: 6.5,
      link: "https://www.clinique.com/product/1574/58208/3-step/step-3-moisturize/dramatically-different-hydrating-jelly?size=15ml_Tube",
      product_img: "ecore/eImages/C_DDHJ.png",
      brand_logo: "ecore/eImages/Clinique_Logo_White.png",
    },
    {
      name: "Clear Improvement Active Charcoal Mask To Clear Pores",
      brand: "Origins",
      category: null,
      price: 14,
      link: "https://www.origins.com/product/15346/62427/skincare/treat/mask/clear-improvement/active-charcoal-mask-to-clear-pores#/sku/98641",
      product_img: "ecore/eImages/O_Mask_Ch.png",
      brand_logo: "ecore/eImages/Origins_Logo.png",
    },
    {
      name: "In Extreme Dimension Lash Mascara",
      brand: "M.A.C",
      category: "3D Black",
      price: 14,
      link: "https://www.maccosmetics.com/product/13839/56446/products/makeup/eyes/mascara/in-extreme-dimension-lash-mascara-mini-mac#/shade/3D_Black",
      product_img: "ecore/eImages/MAC_Masc_IED.png",
      brand_logo: "ecore/eImages/MAC_Logo_White.png",
    },
    {
      name: "Hairdresser's Invisible Oil",
      brand: "Bumble and bumble.",
      category: null,
      price: 23,
      link: "https://www.bumbleandbumble.com/product/19060/23196/style/oils/hairdressers-invisible-oil#/sku/51875",
      product_img: "ecore/eImages/BB_HI_Oil.png",
      brand_logo: "ecore/eImages/B&B_Logo_White.png",
    },
    {
      name: "Retro Matte Liquid Lipcolour",
      brand: "M.A.C",
      category: "Caviar",
      price: 22,
      link: "https://www.maccosmetics.com/product/13854/37620/products/makeup/lips/lipstick/retro-matte-liquid-lipcolour#/shade/Caviar",
      product_img: "ecore/eImages/MAC_LiqLip_C.png",
      brand_logo: "ecore/eImages/MAC_Logo_White.png",
    },
    {
      name: "Chubby Stick Cheek Colour Balm",
      brand: "Clinique",
      category: "Robust Rhubarb",
      price: 26.5,
      link: "https://www.clinique.com/product/1593/30944/makeup/blushers/chubby-stick-cheek-colour-balm?shade=Robust_Rhubarb",
      product_img: "ecore/eImages/C_Chubby_RR.png",
      brand_logo: "ecore/eImages/Clinique_Logo_White.png",
    },
    {
      name: "Always On Liquid Liner",
      brand: "Smashbox",
      category: "Black",
      price: 22,
      link: "https://m.smashbox.com/product/6028/55053/eyes/eye-liner/always-on-liquid-liner?shade=Black&size=0.02_oz%2F0.6g",
      product_img: "ecore/eImages/SB_Liner_AO.png",
      brand_logo: "ecore/eImages/SB_Logo_White.png",
    },
  ],
  cottagecore: [
    {
      name: "Blackberry & Bay Cologne",
      brand: "Jo Malone",
      category: null,
      price: 144,
      link: "https://www.jomalone.com/product/25946/23540/colognes/blackberry-bay-cologne?size=100ml",
      product_img: "cottagecore/ccImages/JM_BB_Cologne.png",
      brand_logo: "cottagecore/ccImages/Jo_Malone_Logo.png",
    },
    {
      name: "botanical repair intensive strengthening masque: light",
      brand: "Aveda",
      category: null,
      price: 12,
      link: "https://www.aveda.com/product/17754/80717/hair-care/treatment-masques/botanical-repair-intensive-strengthening-masque-light#/shade/.85_fl_oz%2F25_ml_-_travel_size",
      product_img: "cottagecore/ccImages/AV_ISM_Hair.png",
      brand_logo: "cottagecore/ccImages/Aveda_Logo.png",
    },
    {
      name: "Lipglass",
      brand: "M.A.C",
      category: "C-Thru",
      price: 15,
      link: "https://www.maccosmetics.com/product/13853/30810/products/makeup/lips/lip-gloss/lipglass-mini-mac#!/shade/C-Thru",
      product_img: "cottagecore/ccImages/MAC_LipG_C.png",
      brand_logo: "cottagecore/ccImages/MAC_Logo.png",
    },
    {
      name: "Travel Size Hangover Pillow Balm Lip Treatment",
      brand: "Too Faced",
      category: null,
      price: 17,
      link: "https://www.toofaced.com/product/24722/86334/skin-care/lip-treatments/travel-size-hangover-pillow-balm-lip-treatment/hydrating-balm-infused-with-fruit-oils-coconut-water",
      product_img: "cottagecore/ccImages/TF_PBalm.png",
      brand_logo: "cottagecore/ccImages/Too_Faced_Logo.webp",
    },
    {
      name: "Cleansing, Retexturizing And Mattifying Trio",
      brand: "Origins",
      category: null,
      price: 15,
      link: "https://www.origins.com/product/15341/85575/skincare/skincare-gifts/skin-prettifiers/cleansing-retexturizing-and-mattifying-trio#/sku/129183",
      product_img: "cottagecore/ccImages/O_Pret_Trio.png",
      brand_logo: "cottagecore/ccImages/Origins_Logo.png",
    },
    {
      name: "3 Little Soaps with Travel Dish - Mild",
      brand: "Clinique",
      category: "Skin Type 2",
      price: 19,
      link: "https://www.clinique.com/product/1572/5168/3-step/step-1-cleanse/3-little-soaps-with-travel-dish--mild?size=4.5_oz_-_Skin_Type_2",
      product_img: "cottagecore/ccImages/C_Soap_Trio.png",
      brand_logo: "cottagecore/ccImages/Clinique_Logo.webp",
    },
    {
      name: "Powder Blush",
      brand: "M.A.C",
      category: "Fleur Power",
      price: 25,
      link: "https://www.maccosmetics.com/product/13842/329/products/makeup/face/blush-bronzer/powder-blush#!/shade/Fleur_Power",
      product_img: "cottagecore/ccImages/MAC_Blush_FP.png",
      brand_logo: "cottagecore/ccImages/MAC_Logo.png",
    },
  ],
};
